# custom aapt2 execute location
android.aapt2FromMavenOverride=/usr/bin/aapt2


android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Android Gradle Plugin 8.12 sa nesmie spustat cez povodnu systemovu Javu 8.
# Toto je skutocna cesta k JDK 17 v pouzivanom Ubuntu prostredi.
org.gradle.java.home=/home/test/.jdks/jdk-17
