package com.marko.turista

data class Country(
    val flag: String,
    val name: String,
    val continent: String
)

object CountryData {

    val countries = listOf(

        // EURÓPA
        Country("🇦🇱", "Albánsko", "Európa"),
        Country("🇦🇩", "Andorra", "Európa"),
        Country("🇦🇹", "Rakúsko", "Európa"),
        Country("🇧🇾", "Bielorusko", "Európa"),
        Country("🇧🇪", "Belgicko", "Európa"),
        Country("🇧🇦", "Bosna a Hercegovina", "Európa"),
        Country("🇧🇬", "Bulharsko", "Európa"),
        Country("🇭🇷", "Chorvátsko", "Európa"),
        Country("🇨🇾", "Cyprus", "Európa"),
        Country("🇨🇿", "Česko", "Európa"),
        Country("🇩🇰", "Dánsko", "Európa"),
        Country("🇪🇪", "Estónsko", "Európa"),
        Country("🇫🇮", "Fínsko", "Európa"),
        Country("🇫🇷", "Francúzsko", "Európa"),
        Country("🇬🇷", "Grécko", "Európa"),
        Country("🇭🇺", "Maďarsko", "Európa"),
        Country("🇮🇸", "Island", "Európa"),
        Country("🇮🇪", "Írsko", "Európa"),
        Country("🇮🇹", "Taliansko", "Európa"),
        Country("🇽🇰", "Kosovo", "Európa"),
        Country("🇱🇻", "Lotyšsko", "Európa"),
        Country("🇱🇮", "Lichtenštajnsko", "Európa"),
        Country("🇱🇹", "Litva", "Európa"),
        Country("🇱🇺", "Luxembursko", "Európa"),
        Country("🇲🇹", "Malta", "Európa"),
        Country("🇲🇩", "Moldavsko", "Európa"),
        Country("🇲🇨", "Monako", "Európa"),
        Country("🇲🇪", "Čierna Hora", "Európa"),
        Country("🇳🇱", "Holandsko", "Európa"),
        Country("🇲🇰", "Severné Macedónsko", "Európa"),
        Country("🇳🇴", "Nórsko", "Európa"),
        Country("🇵🇱", "Poľsko", "Európa"),
        Country("🇵🇹", "Portugalsko", "Európa"),
        Country("🇷🇴", "Rumunsko", "Európa"),
        Country("🇷🇺", "Rusko", "Európa"),
        Country("🇸🇲", "San Maríno", "Európa"),
        Country("🇷🇸", "Srbsko", "Európa"),
        Country("🇸🇰", "Slovensko", "Európa"),
        Country("🇸🇮", "Slovinsko", "Európa"),
        Country("🇪🇸", "Španielsko", "Európa"),
        Country("🇸🇪", "Švédsko", "Európa"),
        Country("🇨🇭", "Švajčiarsko", "Európa"),
        Country("🇹🇷", "Turecko", "Európa"),
        Country("🇺🇦", "Ukrajina", "Európa"),
        Country("🇬🇧", "Spojené kráľovstvo", "Európa"),
        Country("🇻🇦", "Vatikán", "Európa"),

        // ÁZIA
        Country("🇦🇫", "Afganistan", "Ázia"),
        Country("🇸🇦", "Saudská Arábia", "Ázia"),
        Country("🇧🇭", "Bahrajn", "Ázia"),
        Country("🇧🇩", "Bangladéš", "Ázia"),
        Country("🇧🇹", "Bhután", "Ázia"),
        Country("🇧🇳", "Brunej", "Ázia"),
        Country("🇨🇳", "Čína", "Ázia"),
        Country("🇵🇭", "Filipíny", "Ázia"),
        Country("🇮🇳", "India", "Ázia"),
        Country("🇮🇩", "Indonézia", "Ázia"),
        Country("🇮🇶", "Irak", "Ázia"),
        Country("🇮🇷", "Irán", "Ázia"),
        Country("🇮🇱", "Izrael", "Ázia"),
        Country("🇯🇵", "Japonsko", "Ázia"),
        Country("🇯🇴", "Jordánsko", "Ázia"),
        Country("🇰🇭", "Kambodža", "Ázia"),
        Country("🇶🇦", "Katar", "Ázia"),
        Country("🇰🇿", "Kazachstan", "Ázia"),
        Country("🇰🇼", "Kuvajt", "Ázia"),
        Country("🇰🇬", "Kirgizsko", "Ázia"),
        Country("🇱🇦", "Laos", "Ázia"),
        Country("🇱🇧", "Libanon", "Ázia"),
        Country("🇲🇾", "Malajzia", "Ázia"),
        Country("🇲🇳", "Mongolsko", "Ázia"),
        Country("🇲🇲", "Mjanmarsko", "Ázia"),
        Country("🇳🇵", "Nepál", "Ázia"),
        Country("🇴🇲", "Omán", "Ázia"),
        Country("🇵🇰", "Pakistan", "Ázia"),
        Country("🇵🇸", "Palestína", "Ázia"),
        Country("🇸🇬", "Singapur", "Ázia"),
        Country("🇰🇷", "Južná Kórea", "Ázia"),
        Country("🇰🇵", "Severná Kórea", "Ázia"),
        Country("🇱🇰", "Srí Lanka", "Ázia"),
        Country("🇸🇾", "Sýria", "Ázia"),
        Country("🇹🇯", "Tadžikistan", "Ázia"),
        Country("🇹🇭", "Thajsko", "Ázia"),
        Country("🇹🇱", "Východný Timor", "Ázia"),
        Country("🇹🇲", "Turkménsko", "Ázia"),
        Country("🇹🇷", "Turecko", "Ázia"),
        Country("🇺🇿", "Uzbekistan", "Ázia"),
        Country("🇻🇳", "Vietnam", "Ázia"),
        Country("🇦🇪", "Spojené arabské emiráty", "Ázia"),

        // AFRIKA
        Country("🇩🇿", "Alžírsko", "Afrika"),
        Country("🇦🇴", "Angola", "Afrika"),
        Country("🇧🇯", "Benin", "Afrika"),
        Country("🇧🇼", "Botswana", "Afrika"),
        Country("🇧🇫", "Burkina Faso", "Afrika"),
        Country("🇧🇮", "Burundi", "Afrika"),
        Country("🇨🇲", "Kamerun", "Afrika"),
        Country("🇨🇫", "Stredoafrická republika", "Afrika"),
        Country("🇹🇩", "Čad", "Afrika"),
        Country("🇨🇩", "Demokratická republika Kongo", "Afrika"),
        Country("🇪🇬", "Egypt", "Afrika"),
        Country("🇪🇷", "Eritrea", "Afrika"),
        Country("🇪🇹", "Etiópia", "Afrika"),
        Country("🇬🇦", "Gabon", "Afrika"),
        Country("🇬🇲", "Gambia", "Afrika"),
        Country("🇬🇭", "Ghana", "Afrika"),
        Country("🇬🇳", "Guinea", "Afrika"),
        Country("🇨🇮", "Pobrežie Slonoviny", "Afrika"),
        Country("🇰🇪", "Keňa", "Afrika"),
        Country("🇱🇷", "Libéria", "Afrika"),
        Country("🇱🇾", "Líbya", "Afrika"),
        Country("🇲🇬", "Madagaskar", "Afrika"),
        Country("🇲🇼", "Malawi", "Afrika"),
        Country("🇲🇱", "Mali", "Afrika"),
        Country("🇲🇦", "Maroko", "Afrika"),
        Country("🇲🇷", "Mauritánia", "Afrika"),
        Country("🇲🇺", "Maurícius", "Afrika"),
        Country("🇲🇿", "Mozambik", "Afrika"),
        Country("🇳🇦", "Namíbia", "Afrika"),
        Country("🇳🇪", "Niger", "Afrika"),
        Country("🇳🇬", "Nigéria", "Afrika"),
        Country("🇷🇼", "Rwanda", "Afrika"),
        Country("🇸🇳", "Senegal", "Afrika"),
        Country("🇸🇱", "Sierra Leone", "Afrika"),
        Country("🇸🇴", "Somálsko", "Afrika"),
        Country("🇿🇦", "Južná Afrika", "Afrika"),
        Country("🇸🇸", "Južný Sudán", "Afrika"),
        Country("🇸🇩", "Sudán", "Afrika"),
        Country("🇹🇿", "Tanzánia", "Afrika"),
        Country("🇹🇳", "Tunisko", "Afrika"),
        Country("🇺🇬", "Uganda", "Afrika"),
        Country("🇿🇲", "Zambia", "Afrika"),
        Country("🇿🇼", "Zimbabwe", "Afrika"),

        // SEVERNÁ AMERIKA
        Country("🇦🇬", "Antigua a Barbuda", "Severná Amerika"),
        Country("🇧🇸", "Bahamy", "Severná Amerika"),
        Country("🇧🇧", "Barbados", "Severná Amerika"),
        Country("🇧🇿", "Belize", "Severná Amerika"),
        Country("🇨🇦", "Kanada", "Severná Amerika"),
        Country("🇨🇷", "Kostarika", "Severná Amerika"),
        Country("🇨🇺", "Kuba", "Severná Amerika"),
        Country("🇩🇲", "Dominika", "Severná Amerika"),
        Country("🇩🇴", "Dominikánska republika", "Severná Amerika"),
        Country("🇸🇻", "Salvádor", "Severná Amerika"),
        Country("🇬🇩", "Grenada", "Severná Amerika"),
        Country("🇬🇹", "Guatemala", "Severná Amerika"),
        Country("🇭🇹", "Haiti", "Severná Amerika"),
        Country("🇭🇳", "Honduras", "Severná Amerika"),
        Country("🇯🇲", "Jamajka", "Severná Amerika"),
        Country("🇲🇽", "Mexiko", "Severná Amerika"),
        Country("🇳🇮", "Nikaragua", "Severná Amerika"),
        Country("🇵🇦", "Panama", "Severná Amerika"),
        Country("🇰🇳", "Svätý Krištof a Nevis", "Severná Amerika"),
        Country("🇱🇨", "Svätá Lucia", "Severná Amerika"),
        Country("🇻🇨", "Svätý Vincent a Grenadíny", "Severná Amerika"),
        Country("🇹🇹", "Trinidad a Tobago", "Severná Amerika"),
        Country("🇺🇸", "Spojené štáty", "Severná Amerika"),

        // JUŽNÁ AMERIKA
        Country("🇦🇷", "Argentína", "Južná Amerika"),
        Country("🇧🇴", "Bolívia", "Južná Amerika"),
        Country("🇧🇷", "Brazília", "Južná Amerika"),
        Country("🇨🇱", "Čile", "Južná Amerika"),
        Country("🇨🇴", "Kolumbia", "Južná Amerika"),
        Country("🇪🇨", "Ekvádor", "Južná Amerika"),
        Country("🇬🇾", "Guyana", "Južná Amerika"),
        Country("🇵🇾", "Paraguaj", "Južná Amerika"),
        Country("🇵🇪", "Peru", "Južná Amerika"),
        Country("🇸🇷", "Surinam", "Južná Amerika"),
        Country("🇺🇾", "Uruguaj", "Južná Amerika"),
        Country("🇻🇪", "Venezuela", "Južná Amerika"),

        // OCEÁNIA
        Country("🇦🇺", "Austrália", "Oceánia"),
        Country("🇫🇯", "Fidži", "Oceánia"),
        Country("🇰🇮", "Kiribati", "Oceánia"),
        Country("🇲🇭", "Marshallove ostrovy", "Oceánia"),
        Country("🇫🇲", "Mikronézia", "Oceánia"),
        Country("🇳🇷", "Nauru", "Oceánia"),
        Country("🇳🇿", "Nový Zéland", "Oceánia"),
        Country("🇵🇼", "Palau", "Oceánia"),
        Country("🇵🇬", "Papua-Nová Guinea", "Oceánia"),
        Country("🇼🇸", "Samoa", "Oceánia"),
        Country("🇸🇧", "Šalamúnove ostrovy", "Oceánia"),
        Country("🇹🇴", "Tonga", "Oceánia"),
        Country("🇹🇻", "Tuvalu", "Oceánia"),
        Country("🇻🇺", "Vanuatu", "Oceánia"),

        // ANTARKTÍDA
        Country("🇦🇶", "Antarktída", "Antarktída")
    )
}